### ISSUE TITLE
R1 Feedback: responsiveness and multiplayer features

### ISSUE THREAD

**Issue by karl-alex-pauls** [whatisnuclear/simulator#2]
In games like Artemis Bridge Simulator and Space Team multiplayer interactions create a base level of responsiveness by chaining 3-5 work tasks.

If interaction loops have feedback between a similar 3-5 tasks 1 second could be closer an upper limit of interactivity. 50-350ms is typical for real-time multiplayer games, and competitive fps's predict motion and interactions over similar periods.

In a game with a determined rate of play, commands should be queued and rate-limited in order to simplify interactions. Commands should be promptly acknowledged even if the simulation does not update to reflect them for 100's of ms.

**Comment by partofthething** [comment]
It's so great to know some gaming industry professionals. 

Certainly the UI should respond instantly if someone flips a switch or drags a slider to acknowledge the input. In writing R1 I had in mind the power level increasing after actuating a control rod. 50 ms would be excellent for response but I'm just totally unaware of what's possible given the slow Python stack I'm currently envisioning so I went with a easy bar. Sounds like shooting for 350ms would be a more appropriate goal. 

This thing won't be much different from a game. It is a game, really.

**Comment by partofthething** [comment]
With SVG.js examples I've been playing with you get near instantaneous feedback. I think we'll be good once we hook the backend (which is still in its pre-infancy)
